// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

export default function handler(req, res) {
  const fakeData = [
    {
      id: "CPUP12345",
      image: "http://example.com/cpu12345.jpg",
      productName: "Intel Core i7-10700K",
      category: "Processor",
      status: "In Stock",
      price: 349.99,
      description: "Powerful 8-core processor for high-performance computing.",
      keyFeatures: {
        brand: "Intel",
        model: "Core i7-10700K",
        specification: "8 cores, 16 threads",
        socket: "LGA 1200",
        clockSpeed: "3.8 GHz (5.1 GHz Turbo)",
        cache: "16MB SmartCache",
        tdp: "125W",
      },
      individualRating: 4.9,
      averageRating: 4.8,
      reviews: 300,
    },
    {
      id: "MBD67890",
      image: "http://example.com/motherboard67890.jpg",
      productName: "ASUS ROG Strix Z590-E",
      category: "Motherboard",
      status: "Out of Stock",
      price: 289.99,
      description: "High-end motherboard for gaming and content creation.",
      keyFeatures: {
        brand: "ASUS",
        model: "ROG Strix Z590-E",
        specification: "ATX Form Factor",
        socket: "LGA 1200",
        chipset: "Intel Z590",
        memorySlots: "4 x DDR4 DIMM (128GB max)",
        pcieSlots: "3 x PCIe 4.0 x16",
        m2Slots: "3",
        usbPorts: "USB 3.2 Gen 2, USB-C",
      },
      individualRating: 4.7,
      averageRating: 4.6,
      reviews: 250,
    },
    {
      id: "RAM24680",
      image: "http://example.com/ram24680.jpg",
      productName: "Corsair Vengeance LPX 16GB",
      category: "RAM",
      status: "In Stock",
      price: 89.99,
      description: "High-performance DDR4 memory for smooth multitasking.",
      keyFeatures: {
        brand: "Corsair",
        model: "Vengeance LPX",
        specification: "16GB (2 x 8GB) DDR4",
        speed: "3200 MHz",
        casLatency: "16",
        voltage: "1.35V",
        heatSpreader: "Aluminum",
      },
      individualRating: 4.8,
      averageRating: 4.9,
      reviews: 180,
    },
    {
      id: "GPU13579",
      image: "http://example.com/gpu13579.jpg",
      productName: "NVIDIA GeForce RTX 3080",
      category: "GraphicsCard",
      status: "In Stock",
      price: 899.99,
      description: "Powerful graphics card for gaming and rendering.",
      keyFeatures: {
        brand: "NVIDIA",
        model: "GeForce RTX 3080",
        specification: "10GB GDDR6X",
        memoryBus: "320-bit",
        coreClock: "1440 MHz",
        boostClock: "1710 MHz",
        rayTracingCores: "68",
        tensorCores: "272",
      },
      individualRating: 4.9,
      averageRating: 4.9,
      reviews: 350,
    },
    {
      id: "SSD35713",
      image: "http://example.com/ssd35713.jpg",
      productName: "Samsung 970 EVO Plus 1TB",
      category: "Storage",
      status: "In Stock",
      price: 159.99,
      description: "High-speed NVMe SSD for faster data access.",
      keyFeatures: {
        brand: "Samsung",
        model: "970 EVO Plus",
        specification: "1TB NVMe M.2",
        readSpeed: "3500 MB/s",
        writeSpeed: "3300 MB/s",
        interface: "PCIe 3.0 x4",
        formFactor: "M.2 2280",
        nandFlash: "3-bit MLC V-NAND",
      },
      individualRating: 4.7,
      averageRating: 4.8,
      reviews: 280,
    },
    {
      id: "PSU46802",
      image: "http://example.com/psu46802.jpg",
      productName: "EVGA SuperNOVA 850 G3",
      category: "PowerSupply",
      status: "In Stock",
      price: 129.99,
      description: "High-efficiency power supply for reliable performance.",
      keyFeatures: {
        brand: "EVGA",
        model: "SuperNOVA 850 G3",
        specification: "850W 80+ Gold",
        modularity: "Fully Modular",
        fanSize: "130mm",
        protection: "OVP, UVP, OCP, OPP, SCP, OTP",
      },
      individualRating: 4.8,
      averageRating: 4.7,
      reviews: 220,
    },
    {
      id: "CASE58024",
      image: "http://example.com/case58024.jpg",
      productName: "NZXT H510i",
      category: "ComputerCase",
      status: "Out of Stock",
      price: 99.99,
      description: "Sleek and compact mid-tower case with RGB lighting.",
      keyFeatures: {
        brand: "NZXT",
        model: "H510i",
        specification: "Mid-Tower",
        motherboardSupport: "ATX, MicroATX, Mini-ITX",
        coolingSupport: "Up to 3 x 120mm or 2 x 140mm",
        frontPanelPorts: "2 x USB 3.0, 1 x USB-C, Audio",
      },
      individualRating: 4.7,
      averageRating: 4.6,
      reviews: 190,
    },
  ];
  res.status(200).json({ data: fakeData });
}
